import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { ArrowRight, Check, Clock3, Download, Home, Mail, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";

export const Route = createFileRoute("/order-success")({ component: SuccessPage });
function SuccessPage() {
  const navigate = useNavigate();
  const [order, setOrder] = useState<any>(null);
  useEffect(() => { try { setOrder(JSON.parse(localStorage.getItem("yj-last-order") || "null")); } catch { setOrder(null); } }, []);
  const status = ["Eingegangen", "Wird frisch zubereitet", "Abholbereit an der Theke", "Abgeschlossen"];
  return <main className="min-h-screen bg-[#f8f6f0] px-4 py-8 text-[#1f2022] sm:px-8"><div className="mx-auto max-w-2xl"><div className="text-center"><div className="mx-auto flex size-20 items-center justify-center rounded-full bg-[#dcead5] text-[#4f7041] shadow-sm"><Check /></div><p className="mt-6 text-xs font-bold uppercase tracking-[.2em] text-[#c46b38]">Bestellung bestätigt</p><h1 className="mt-2 font-display text-5xl">{order?.order || "#YJ-2481"}</h1><p className="mt-3 text-lg text-[#6f675f]">Abholbereit um ca. 14:35 Uhr</p></div><Card className="mt-8 border-[#e2d8ca] bg-white/80 shadow-sm"><CardHeader><CardTitle>Live-Status</CardTitle><CardDescription>Wir halten dich auf dem Laufenden.</CardDescription></CardHeader><CardContent><div className="grid gap-3">{status.map((label, index) => <div key={label} className={`flex items-center gap-3 rounded-2xl border p-4 ${index === 0 ? "border-[#c46b38] bg-[#fff7f1]" : "border-[#eee5dc]"}`}><span className={`flex size-8 shrink-0 items-center justify-center rounded-full text-sm font-bold ${index === 0 ? "bg-[#c46b38] text-white" : "bg-[#eee5dc] text-[#9a9085]"}`}>{index + 1}</span><span className={index === 0 ? "font-semibold" : "text-[#9a9085]"}>{label}</span>{index === 0 && <Badge className="ml-auto bg-[#dcead5] text-[#4f7041]">Aktiv</Badge>}</div>)}</div></CardContent></Card><Card className="mt-6 border-[#e2d8ca] bg-[#1f2022] text-[#f8f6f0] shadow-xl"><CardContent className="flex items-start gap-4 p-6"><Mail className="mt-1 text-[#d9946d]" /><p className="text-sm leading-6 text-[#ded3c9]">Eine Bestätigung und dein digitaler Kassenbeleg wurden an <strong className="text-white">{order?.contact?.email || "deine E-Mail-Adresse"}</strong> gesendet.</p></CardContent></Card><Card className="mt-6 border-[#e2d8ca] bg-white/80"><CardHeader><CardTitle className="flex items-center gap-2"><Sparkles className="text-[#c46b38]" />Noch schneller beim nächsten Mal</CardTitle><CardDescription>Möchtest du deine Daten sichern und Punkte sammeln?</CardDescription></CardHeader><CardContent><Button variant="outline" className="w-full rounded-full border-[#c46b38] text-[#a6532d]">Konto ohne Passwort aktivieren <ArrowRight data-icon="inline-end" /></Button><p className="mt-3 text-center text-xs text-[#9a9085]">Wir schicken dir einen Magic-Link an deine E-Mail.</p></CardContent></Card><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button onClick={() => navigate({ to: "/" })} className="h-12 flex-1 rounded-full bg-[#1f2022] text-white"><Home data-icon="inline-start" />Zur Startseite</Button><Button variant="outline" onClick={() => window.print()} className="h-12 flex-1 rounded-full"><Download data-icon="inline-start" />Bon herunterladen</Button></div><div className="mt-8 flex items-center justify-center gap-2 text-xs text-[#9a9085]"><Clock3 />Abholung in Hanau · Willy-Brandt-Straße 23</div><Separator className="mt-6 bg-[#e2d8ca]" /></div></main>;
}
export default SuccessPage;
