import { createFileRoute } from "@tanstack/react-router";
import { Check, ChevronDown, Minus, Plus, ShoppingBag, Trash2, X } from "lucide-react";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Textarea } from "@/components/ui/textarea";
import { bowls, matchas, acais, iceBurgerImage, wrapImage, type Bowl } from "@/lib/menu-data";

export const Route = createFileRoute("/speisekarte")({ component: OrderPage });
type CartItem = { id: string; name: string; detail: string; price: number; image: string; qty: number };
const euro = (value: number) => `${value.toFixed(2).replace(".", ",")} €`;

function OrderPage() {
  const [cart, setCart] = useState<CartItem[]>([]);
  const [drawer, setDrawer] = useState(false);
  const [selected, setSelected] = useState<Bowl | null>(null);
  const [checkout, setCheckout] = useState(false);
  const [confirmed, setConfirmed] = useState(false);
  const [category, setCategory] = useState("Bowls");
  const count = cart.reduce((sum, item) => sum + item.qty, 0);
  const total = cart.reduce((sum, item) => sum + item.price * item.qty, 0);
  const add = (item: CartItem) => setCart((current) => { const found = current.find((entry) => entry.id === item.id); return found ? current.map((entry) => entry.id === item.id ? { ...entry, qty: entry.qty + item.qty } : entry) : [...current, item]; });
  const change = (id: string, amount: number) => setCart((current) => current.map((item) => item.id === id ? { ...item, qty: item.qty + amount } : item).filter((item) => item.qty > 0));
  const categories = ["Bowls", "Açaí", "Iced Matcha", "Ice Burger", "Wraps"];
  const products = useMemo(() => category === "Bowls" ? bowls : [], [category]);

  if (confirmed) return <Confirmation onBack={() => { setConfirmed(false); setCart([]); }} />;
  return <main className="min-h-screen bg-[#f5f0e8] text-[#262421]">
    <div className="mx-auto max-w-7xl px-5 pb-28 pt-8 sm:px-8">
      <header className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#a85b39]">Click & Collect · Hanau</p><h1 className="mt-3 max-w-2xl font-display text-5xl leading-[.9] sm:text-7xl">Frisch. Schnell.<br/><em className="text-[#a85b39]">Deins.</em></h1><p className="mt-5 max-w-lg text-base leading-7 text-[#6f675f]">Bestelle deine Lieblings-Bowl online und hol sie frisch zubereitet bei Yamiin & Jaiyana&apos;s ab.</p></div><Button onClick={() => setDrawer(true)} className="relative rounded-full bg-[#292725] text-[#f5f0e8] hover:bg-[#a85b39]" aria-label="Warenkorb öffnen"><ShoppingBag data-icon="inline-start"/>Warenkorb{count > 0 && <Badge className="absolute -right-2 -top-2 bg-[#c87850] text-white">{count}</Badge>}</Button></header>
      <nav className="mt-12 flex gap-2 overflow-x-auto pb-2" aria-label="Kategorien">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`whitespace-nowrap rounded-full border px-5 py-2.5 text-sm font-semibold transition ${category === item ? "border-[#292725] bg-[#292725] text-white" : "border-[#d9cec0] bg-white/60 hover:border-[#a85b39]"}`}>{item}</button>)}</nav>
      {category === "Bowls" && <section className="mt-10"><div className="mb-6 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#a85b39]">Signature Bowls</p><h2 className="mt-2 font-display text-4xl">Deine <em>Bowl</em></h2></div><span className="hidden text-sm text-[#6f675f] sm:block">Base nach Wahl · frisch zubereitet</span></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{products.map((bowl) => <BowlCard key={bowl.name} bowl={bowl} onSelect={() => setSelected(bowl)} />)}</div></section>}
      {category === "Açaí" && <ProductGrid title="Açaí Specials" items={acais.map((item) => ({ ...item, price: 11.9 }))} onAdd={add} />}
      {category === "Iced Matcha" && <ProductGrid title="Iced Matcha" items={matchas.map((item) => ({ ...item, price: Number(item.price.replace(",", ".").replace(" €", "")) }))} onAdd={add} />}
      {category === "Ice Burger" && <ProductGrid title="Peeka Ice Burger" items={["Peeka Pistachio", "Peeka Lotus", "Peeka Bueno"].map((name) => ({ name, description: "Gefüllt mit Ice Cream", price: 4, image: iceBurgerImage }))} onAdd={add} />}
      {category === "Wraps" && <ProductGrid title="Wrap it up!" items={[{ name: "Chicken Wrap", description: "Chicken, Salat, Gemüse & Sauce", price: 8.9, image: wrapImage }]} onAdd={add} />}
    </div>
    <Button onClick={() => setDrawer(true)} className="fixed bottom-5 right-5 z-20 rounded-full bg-[#c87850] px-5 py-6 text-white shadow-xl hover:bg-[#a85b39]"><ShoppingBag data-icon="inline-start"/>Warenkorb {count > 0 && `· ${euro(total)}`}</Button>
    <Sheet open={drawer} onOpenChange={setDrawer}><SheetContent className="w-full border-l-[#d9cec0] bg-[#fffaf4] sm:max-w-md"><SheetHeader><SheetTitle className="font-display text-3xl">Dein Warenkorb</SheetTitle><SheetDescription>{count ? `${count} Artikel · Abholung in Hanau` : "Noch ist dein Warenkorb leer."}</SheetDescription></SheetHeader><div className="flex h-full flex-col px-6 pb-6">{cart.length === 0 ? <div className="flex flex-1 items-center justify-center text-center text-[#6f675f]">Füge deine Favoriten hinzu und hole sie frisch bei uns ab.</div> : <><div className="flex-1 overflow-y-auto py-6">{cart.map((item) => <div key={item.id} className="flex gap-3 border-b border-[#eadfd2] py-4"><img src={item.image} alt="" className="size-16 rounded-xl bg-[#f1e8dc] object-contain"/><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><p className="font-semibold">{item.name}</p><button onClick={() => change(item.id, -item.qty)} aria-label={`${item.name} löschen`}><Trash2 className="size-4 text-[#a85b39]"/></button></div><p className="text-xs text-[#6f675f]">{item.detail}</p><div className="mt-2 flex items-center justify-between"><div className="flex items-center gap-2 rounded-full border border-[#d9cec0] px-2"><button onClick={() => change(item.id, -1)} aria-label="Weniger"><Minus className="size-3"/></button><span className="text-sm">{item.qty}</span><button onClick={() => change(item.id, 1)} aria-label="Mehr"><Plus className="size-3"/></button></div><strong>{euro(item.price * item.qty)}</strong></div></div></div>)}</div><div className="border-t border-[#d9cec0] pt-5"><div className="flex justify-between text-lg font-bold"><span>Zwischensumme</span><span>{euro(total)}</span></div><Button onClick={() => { setDrawer(false); setCheckout(true); }} className="mt-4 w-full rounded-full bg-[#292725] py-6 text-white hover:bg-[#a85b39]">Zur Kasse</Button></div></>}</div></SheetContent></Sheet>
    <Dialog open={Boolean(selected)} onOpenChange={() => setSelected(null)}><DialogContent className="max-h-[90vh] overflow-y-auto bg-[#fffaf4]"><DialogHeader><DialogTitle className="font-display text-3xl">{selected?.name}</DialogTitle><DialogDescription>{selected?.description}</DialogDescription></DialogHeader>{selected && <div className="grid gap-5"><img src={selected.image} alt={selected.name} className="mx-auto aspect-square max-h-56 w-full rounded-2xl bg-[#f1e8dc] object-contain"/><div><Label>Größe</Label><div className="mt-2 grid grid-cols-2 gap-2"><Button variant="outline" onClick={() => add({ id: selected.name + "-klein", name: selected.name, detail: "Klein · Bulgur", price: Number(selected.small.replace(",", ".").replace(" €", "")), image: selected.image, qty: 1 })}>Klein · {selected.small}</Button><Button onClick={() => add({ id: selected.name + "-gross", name: selected.name, detail: "Groß · Bulgur", price: Number(selected.large.replace(",", ".").replace(" €", "")), image: selected.image, qty: 1 })} className="bg-[#292725]">Groß · {selected.large}</Button></div></div><div><Label htmlFor="base">Basis</Label><select id="base" className="mt-2 w-full rounded-md border border-[#d9cec0] bg-white p-3"><option>Bulgur</option><option>Somalireis</option><option>Salat</option></select></div><div><Label htmlFor="note">Notiz an die Küche</Label><Textarea id="note" placeholder="z. B. keine Zwiebeln" className="mt-2 bg-white"/></div></div>}<DialogFooter><Button variant="ghost" onClick={() => setSelected(null)}>Schließen</Button></DialogFooter></DialogContent></Dialog>
    <Checkout open={checkout} onOpenChange={setCheckout} total={total} onComplete={() => { setCheckout(false); setConfirmed(true); }} />
  </main>;
}

function BowlCard({ bowl, onSelect }: { bowl: Bowl; onSelect: () => void }) { return <article className="overflow-hidden rounded-2xl border border-[#dfd3c5] bg-[#fffaf4] shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="relative bg-[#eee5d9]"><span className="absolute left-4 top-4 z-10 rounded-full bg-white px-3 py-1 text-xs font-bold">{bowl.tag}</span><img src={bowl.image} alt={bowl.name} className="aspect-square w-full object-contain p-5"/></div><div className="p-5"><h3 className="font-display text-2xl">{bowl.name}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-[#6f675f]">{bowl.description}</p><div className="mt-5 flex items-center justify-between border-t border-[#eadfd2] pt-4"><div><span className="text-xs text-[#6f675f]">ab</span><p className="text-xl font-bold">{bowl.small}</p></div><Button onClick={onSelect} className="rounded-full bg-[#292725] text-white hover:bg-[#a85b39]">Auswählen</Button></div></div></article>; }
function ProductGrid({ title, items, onAdd }: { title: string; items: any[]; onAdd: (item: CartItem) => void }) { return <section className="mt-10"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#a85b39]">Frisch für dich</p><h2 className="mt-2 font-display text-4xl">{title}</h2><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{items.map((item) => <article key={item.name} className="overflow-hidden rounded-2xl border border-[#dfd3c5] bg-[#fffaf4]"><img src={item.image} alt={item.name} className="aspect-square w-full bg-[#eee5d9] object-contain p-4"/><div className="p-5"><h3 className="font-display text-xl">{item.name}</h3><p className="mt-2 min-h-10 text-sm text-[#6f675f]">{item.description}</p><div className="mt-4 flex items-center justify-between"><strong>{euro(item.price)}</strong><Button size="sm" onClick={() => onAdd({ id: item.name, name: item.name, detail: "Standard", price: item.price, image: item.image, qty: 1 })} className="rounded-full bg-[#292725] text-white"><Plus data-icon="inline-start"/>Hinzufügen</Button></div></div></article>)}</div></section>; }
function Checkout({ open, onOpenChange, total, onComplete }: { open: boolean; onOpenChange: (open: boolean) => void; total: number; onComplete: () => void }) { const [step, setStep] = useState(1); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="bg-[#fffaf4]"><DialogHeader><DialogTitle className="font-display text-3xl">Bestellung abschließen</DialogTitle><DialogDescription>Schritt {step} von 3 · Abholung bei Yamiin & Jaiyana&apos;s, Hanau</DialogDescription></DialogHeader>{step === 1 && <div className="grid gap-4"><Field label="Vor- und Nachname" placeholder="Dein Name"/><Field label="Telefonnummer" placeholder="Für Rückfragen"/><Field label="E-Mail" placeholder="Für die Bestätigung" type="email"/></div>}{step === 2 && <div className="grid gap-3"><Button variant="outline" className="h-auto justify-start p-4 text-left" onClick={() => setStep(3)}><span><strong>So schnell wie möglich</strong><br/><small className="text-[#6f675f]">ca. 20–30 Minuten</small></span></Button><Button variant="outline" className="h-auto justify-start p-4 text-left" onClick={() => setStep(3)}><span><strong>Wunsch-Uhrzeit heute</strong><br/><small className="text-[#6f675f]">Wir zeigen dir verfügbare Zeiten</small></span></Button></div>}{step === 3 && <div className="grid gap-3"><Button variant="outline" className="h-auto justify-start p-4 text-left" onClick={onComplete}><span><strong>Vor Ort bei Abholung</strong><br/><small className="text-[#6f675f]">Barzahlung oder EC/Kreditkarte</small></span></Button><Button className="h-auto justify-start bg-[#292725] p-4 text-left text-white" onClick={onComplete}><span><strong>Online sofort zahlen</strong><br/><small className="text-white/70">PayPal, Apple Pay, Google Pay oder Karte</small></span></Button></div>}<DialogFooter>{step === 1 && <Button onClick={() => setStep(2)} className="w-full rounded-full bg-[#292725]">Weiter</Button>}{step > 1 && <Button variant="ghost" onClick={() => setStep(step - 1)}>Zurück</Button>}<span className="ml-auto self-center font-bold">{euro(total)}</span></DialogFooter></DialogContent></Dialog>; }
function Field({ label, placeholder, type = "text" }: { label: string; placeholder: string; type?: string }) { return <div className="grid gap-2"><Label>{label}</Label><Input type={type} placeholder={placeholder} className="bg-white"/></div>; }
function Confirmation({ onBack }: { onBack: () => void }) { return <main className="flex min-h-screen items-center justify-center bg-[#f5f0e8] px-5"><div className="w-full max-w-lg rounded-3xl bg-[#fffaf4] p-8 text-center shadow-xl sm:p-12"><div className="mx-auto flex size-16 items-center justify-center rounded-full bg-[#dbe7d1] text-[#4f7041]"><Check /></div><p className="mt-6 text-xs font-bold uppercase tracking-[.18em] text-[#a85b39]">Bestellung bestätigt</p><h1 className="mt-3 font-display text-5xl">Danke, wir freuen uns!</h1><p className="mt-5 text-[#6f675f]">Deine Bestellung <strong>#YJ-{Math.floor(1000 + Math.random() * 8999)}</strong> ist bei uns eingegangen. Wir bereiten alles frisch für dich zu.</p><Button onClick={onBack} className="mt-8 rounded-full bg-[#292725] text-white">Weitere Bestellung</Button></div></main>; }

