import { createFileRoute } from "@tanstack/react-router";
import { Check, ChevronLeft, Minus, Plus, ShoppingBag, SlidersHorizontal, Trash2 } from "lucide-react";
import { useMemo, useRef, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Textarea } from "@/components/ui/textarea";
import { acais, bowls, iceBurgerImage, matchas, wrapImage, type Bowl } from "@/lib/menu-data";

export const Route = createFileRoute("/speisekarte")({ component: OrderPage });
type CartItem = { id: string; name: string; detail: string; price: number; image: string; qty: number };
const euro = (value: number) => `${value.toFixed(2).replace(".", ",")} €`;
const parsePrice = (value: string) => Number(value.replace(",", ".").replace(" €", ""));
const categories = ["Bowls", "Açaí", "Iced Matcha", "Ice Burger", "Wraps"];

function OrderPage() {
  const [cart, setCart] = useState<CartItem[]>([]);
  const [category, setCategory] = useState("Bowls");
  const [drawer, setDrawer] = useState(false);
  const [selected, setSelected] = useState<Bowl | null>(null);
  const [checkout, setCheckout] = useState(false);
  const [confirmed, setConfirmed] = useState(false);
  const [orderNumber, setOrderNumber] = useState("");
  const categoryNavRef = useRef<HTMLElement>(null);
  const count = cart.reduce((sum, item) => sum + item.qty, 0);
  const total = cart.reduce((sum, item) => sum + item.price * item.qty, 0);
  const add = (item: CartItem) => setCart((current) => { const found = current.find((entry) => entry.id === item.id); return found ? current.map((entry) => entry.id === item.id ? { ...entry, qty: entry.qty + item.qty } : entry) : [...current, item]; });
  const change = (id: string, amount: number) => setCart((current) => current.map((item) => item.id === id ? { ...item, qty: item.qty + amount } : item).filter((item) => item.qty > 0));
  const products = useMemo(() => category === "Bowls" ? bowls : [], [category]);
  if (confirmed) return <Confirmation orderNumber={orderNumber} onBack={() => { setConfirmed(false); setCart([]); }} />;

  return <main className="min-h-screen bg-[#f5f0e8] text-[#292725]">
    <div className="mx-auto max-w-7xl px-5 pb-28 pt-8 sm:px-8">
      <header className="relative overflow-hidden rounded-[2rem] bg-[#292725] px-6 py-8 text-[#f5f0e8] shadow-xl sm:px-10 sm:py-10"><div className="absolute -right-20 -top-24 size-72 rounded-full bg-[#a85b39]/30 blur-3xl" /><div className="relative flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#d9946d]">Click & Collect · Hanau</p><h1 className="mt-3 max-w-2xl font-display text-5xl leading-[.9] sm:text-7xl">Frisch. Schnell.<br /><em className="text-[#d9946d]">Deins.</em></h1><p className="mt-5 max-w-lg text-base leading-7 text-[#eadfd2]">Bestelle deine Lieblingsgerichte online und hole sie frisch zubereitet bei Yamiin & Jaiyana&apos;s ab.</p></div><Button onClick={() => setDrawer(true)} className="relative hidden rounded-full bg-[#f5f0e8] text-[#292725] hover:bg-[#d9946d] sm:inline-flex"><ShoppingBag data-icon="inline-start" />Warenkorb{count > 0 && <Badge className="absolute -right-2 -top-2 bg-[#c87850] text-white">{count}</Badge>}</Button></div></header>
      <nav ref={categoryNavRef} id="menu-categories" className="sticky top-[4.5rem] z-30 -mx-5 mt-12 flex gap-2 overflow-x-auto border-y border-[#d9cec0] bg-[#f5f0e8]/95 px-5 py-3 backdrop-blur-md sm:-mx-8 sm:px-8" aria-label="Kategorien">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`whitespace-nowrap rounded-full border px-5 py-2.5 text-sm font-semibold transition ${category === item ? "border-[#292725] bg-[#292725] text-white" : "border-[#d9cec0] bg-white/60 hover:border-[#a85b39]"}`}>{item}</button>)}</nav>
      {category === "Bowls" && <section className="mt-10"><div className="mb-6 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#a85b39]">Signature Bowls</p><h2 className="mt-2 font-display text-4xl">Deine <em>Bowl</em></h2></div><span className="hidden text-sm text-[#6f675f] sm:block">Base nach Wahl · frisch zubereitet</span></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{products.map((bowl) => <BowlCard key={bowl.name} bowl={bowl} onSelect={() => setSelected(bowl)} />)}</div></section>}
      {category === "Açaí" && <ProductGrid title="Açaí Specials" items={acais.map((item) => ({ ...item, price: 11.9 }))} onAdd={add} />}
      {category === "Iced Matcha" && <ProductGrid title="Iced Matcha" items={matchas.map((item) => ({ ...item, price: parsePrice(item.price) }))} onAdd={add} />}
      {category === "Ice Burger" && <ProductGrid title="Peeka Ice Burger" items={["Peeka Pistachio", "Peeka Lotus", "Peeka Bueno"].map((name) => ({ name, description: "Gefüllt mit Ice Cream", price: 4, image: iceBurgerImage }))} onAdd={add} />}
      {category === "Wraps" && <ProductGrid title="Wrap it up!" items={[{ name: "Chicken Wrap", description: "Chicken, Salat, Gemüse & Sauce", price: 8.9, image: wrapImage }]} onAdd={add} />}
    </div>
    <div className="fixed inset-x-3 bottom-3 z-40 flex items-center gap-2 rounded-2xl border border-white/10 bg-[#292725]/95 p-2 text-[#f5f0e8] shadow-2xl shadow-[#292725]/30 backdrop-blur-xl md:hidden" role="toolbar" aria-label="Bestellaktionen"><Button type="button" variant="ghost" size="icon" aria-label="Kategorien anzeigen" onClick={() => categoryNavRef.current?.scrollIntoView({ behavior: "smooth", block: "center" })} className="size-12 shrink-0 rounded-xl text-[#f5f0e8] hover:bg-white/10 hover:text-[#f5f0e8]"><SlidersHorizontal /></Button><button type="button" onClick={() => setDrawer(true)} className="flex min-w-0 flex-1 items-center gap-3 rounded-xl px-2 text-left outline-none transition hover:bg-white/10 focus-visible:ring-2 focus-visible:ring-[#d9946d]"><span className="relative flex size-10 shrink-0 items-center justify-center rounded-full bg-[#c87850] text-white"><ShoppingBag /><span className="absolute -right-1 -top-1 flex size-5 items-center justify-center rounded-full bg-[#f5f0e8] text-[10px] font-bold text-[#292725]">{count}</span></span><span className="min-w-0"><span className="block truncate text-sm font-semibold">{count ? `${count} Artikel` : "Warenkorb"}</span><span className="block text-xs text-[#cfc2b5]">{euro(total)}</span></span></button><Button type="button" onClick={() => { if (count) { setDrawer(true); } }} disabled={!count} className="h-12 shrink-0 rounded-xl bg-[#f5f0e8] px-4 font-bold text-[#292725] hover:bg-[#d9946d] disabled:opacity-40">Bestellen <ChevronLeft className="ml-1 rotate-180" /></Button></div>
    <Sheet open={drawer} onOpenChange={setDrawer}><SheetContent className="w-full border-l-[#d9cec0] bg-[#fffaf4] sm:max-w-md"><SheetHeader><SheetTitle className="font-display text-3xl">Dein Warenkorb</SheetTitle><SheetDescription>{count ? `${count} Artikel · Abholung in Hanau` : "Noch ist dein Warenkorb leer."}</SheetDescription></SheetHeader><div className="flex h-full flex-col px-6 pb-6">{cart.length === 0 ? <div className="flex flex-1 items-center justify-center text-center text-[#6f675f]">Füge deine Favoriten hinzu und hole sie frisch bei uns ab.</div> : <><div className="flex-1 overflow-y-auto py-6">{cart.map((item) => <div key={item.id} className="flex gap-3 border-b border-[#eadfd2] py-4"><img src={item.image} alt="" className="size-16 rounded-xl bg-[#f1e8dc] object-contain" /><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><p className="font-semibold">{item.name}</p><button onClick={() => change(item.id, -item.qty)} aria-label={`${item.name} löschen`}><Trash2 className="size-4 text-[#a85b39]" /></button></div><p className="text-xs text-[#6f675f]">{item.detail}</p><div className="mt-2 flex items-center justify-between"><div className="flex items-center gap-2 rounded-full border border-[#d9cec0] px-2"><button onClick={() => change(item.id, -1)} aria-label="Weniger"><Minus className="size-3" /></button><span className="text-sm">{item.qty}</span><button onClick={() => change(item.id, 1)} aria-label="Mehr"><Plus className="size-3" /></button></div><strong>{euro(item.price * item.qty)}</strong></div></div></div>)}</div><div className="border-t border-[#d9cec0] pt-5"><div className="flex justify-between text-lg font-bold"><span>Zwischensumme</span><span>{euro(total)}</span></div><Button onClick={() => { setDrawer(false); setCheckout(true); }} className="mt-4 w-full rounded-full bg-[#292725] py-6 text-white hover:bg-[#a85b39]">Zur Kasse</Button></div></>}</div></SheetContent></Sheet>
    <BowlDialog bowl={selected} onClose={() => setSelected(null)} onAdd={add} />
    <Checkout open={checkout} onOpenChange={setCheckout} total={total} onComplete={() => { setCheckout(false); setOrderNumber(`#YJ-${Math.floor(1000 + Math.random() * 8999)}`); setConfirmed(true); }} />
  </main>;
}

function BowlCard({ bowl, onSelect }: { bowl: Bowl; onSelect: () => void }) { return <article className="overflow-hidden rounded-2xl border border-[#dfd3c5] bg-[#fffaf4] shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="relative bg-[#eee5d9]"><span className="absolute left-4 top-4 z-10 rounded-full bg-white px-3 py-1 text-xs font-bold">{bowl.tag}</span><img src={bowl.image} alt={bowl.name} className="aspect-square w-full object-contain p-5" /></div><div className="p-5"><h3 className="font-display text-2xl">{bowl.name}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-[#6f675f]">{bowl.description}</p><div className="mt-5 flex items-center justify-between border-t border-[#eadfd2] pt-4"><div><span className="text-xs text-[#6f675f]">ab</span><p className="text-xl font-bold">{bowl.small}</p></div><Button onClick={onSelect} className="rounded-full bg-[#292725] text-white hover:bg-[#a85b39]">Auswählen</Button></div></div></article>; }
function ProductGrid({ title, items, onAdd }: { title: string; items: { name: string; description: string; price: number; image: string }[]; onAdd: (item: CartItem) => void }) { return <section className="mt-10"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#a85b39]">Frisch für dich</p><h2 className="mt-2 font-display text-4xl">{title}</h2><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{items.map((item) => <article key={item.name} className="overflow-hidden rounded-2xl border border-[#dfd3c5] bg-[#fffaf4]"><img src={item.image} alt={item.name} className="aspect-square w-full bg-[#eee5d9] object-contain p-4" /><div className="p-5"><h3 className="font-display text-xl">{item.name}</h3><p className="mt-2 min-h-10 text-sm text-[#6f675f]">{item.description}</p><div className="mt-4 flex items-center justify-between"><strong>{euro(item.price)}</strong><Button size="sm" onClick={() => onAdd({ id: item.name, name: item.name, detail: "Standard", price: item.price, image: item.image, qty: 1 })} className="rounded-full bg-[#292725] text-white"><Plus data-icon="inline-start" />Hinzufügen</Button></div></div></article>)}</div></section>; }
function BowlDialog({ bowl, onClose, onAdd }: { bowl: Bowl | null; onClose: () => void; onAdd: (item: CartItem) => void }) { const [size, setSize] = useState<"klein" | "gross">("klein"); const [base, setBase] = useState("Bulgur"); const [note, setNote] = useState(""); const [qty, setQty] = useState(1); if (!bowl) return null; const price = size === "klein" ? parsePrice(bowl.small) : parsePrice(bowl.large); return <Dialog open={Boolean(bowl)} onOpenChange={onClose}><DialogContent className="max-h-[90vh] overflow-y-auto bg-[#fffaf4]"><DialogHeader><DialogTitle className="font-display text-3xl">{bowl.name}</DialogTitle><DialogDescription>{bowl.description}</DialogDescription></DialogHeader><div className="grid gap-5"><img src={bowl.image} alt={bowl.name} className="mx-auto aspect-square max-h-52 w-full rounded-2xl bg-[#f1e8dc] object-contain" /><div><Label>Größe</Label><div className="mt-2 grid grid-cols-2 gap-2">{([["klein", bowl.small], ["gross", bowl.large]] as const).map(([value, label]) => <Button key={value} variant={size === value ? "default" : "outline"} onClick={() => setSize(value)} className={size === value ? "bg-[#292725]" : ""}>{value === "klein" ? "Klein" : "Groß"} · {label}</Button>)}</div></div><div><Label htmlFor="base">Basis</Label><select id="base" value={base} onChange={(event) => setBase(event.target.value)} className="mt-2 w-full rounded-md border border-[#d9cec0] bg-white p-3"><option>Bulgur</option><option>Somalireis</option><option>Salat</option></select></div><div><Label htmlFor="note">Notiz an die Küche</Label><Textarea id="note" value={note} onChange={(event) => setNote(event.target.value)} placeholder="z. B. keine Zwiebeln" className="mt-2 bg-white" /></div><div className="flex items-center justify-between"><div className="flex items-center gap-3 rounded-full border border-[#d9cec0] px-3 py-2"><button onClick={() => setQty(Math.max(1, qty - 1))} aria-label="Weniger"><Minus className="size-4" /></button><span>{qty}</span><button onClick={() => setQty(qty + 1)} aria-label="Mehr"><Plus className="size-4" /></button></div><Button onClick={() => { onAdd({ id: `${bowl.name}-${size}-${base}-${note}`, name: bowl.name, detail: `${size === "klein" ? "Klein" : "Groß"} · ${base}${note ? ` · ${note}` : ""}`, price, image: bowl.image, qty }); setQty(1); setNote(""); onClose(); }} className="rounded-full bg-[#a85b39] px-6 text-white">In den Warenkorb · {euro(price * qty)}</Button></div></div></DialogContent></Dialog>; }
function Checkout({ open, onOpenChange, total, onComplete }: { open: boolean; onOpenChange: (open: boolean) => void; total: number; onComplete: () => void }) { const [step, setStep] = useState(1); const [payment, setPayment] = useState(""); const [contact, setContact] = useState({ name: "", phone: "", email: "" }); const [pickup, setPickup] = useState("Schnellstmöglich"); const canContinue = step === 1 ? Object.values(contact).every(Boolean) : step === 2 ? Boolean(pickup) : Boolean(payment); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="bg-[#fffaf4]"><DialogHeader><DialogTitle className="font-display text-3xl">Bestellung abschließen</DialogTitle><DialogDescription>Schritt {step} von 3 · Abholung bei Yamiin & Jaiyana&apos;s, Hanau</DialogDescription></DialogHeader>{step === 1 && <div className="grid gap-4">{([["name", "Vor- und Nachname", "Dein Name"], ["phone", "Telefonnummer", "Für Rückfragen"], ["email", "E-Mail", "Für die Bestätigung"]] as const).map(([key, label, placeholder]) => <div key={key} className="grid gap-2"><Label htmlFor={key}>{label}</Label><Input id={key} value={contact[key]} onChange={(event) => setContact({ ...contact, [key]: event.target.value })} placeholder={placeholder} type={key === "email" ? "email" : "text"} className="bg-white" /></div>)}</div>}{step === 2 && <div className="grid gap-3"><Button variant={pickup === "Schnellstmöglich" ? "default" : "outline"} className="h-auto justify-start p-4 text-left" onClick={() => setPickup("Schnellstmöglich")}> <span><strong>So schnell wie möglich</strong><br /><small className="text-[#6f675f]">ca. 20–30 Minuten</small></span></Button><Button variant={pickup !== "Schnellstmöglich" ? "default" : "outline"} className="h-auto justify-start p-4 text-left" onClick={() => setPickup("Heute 13:00")}> <span><strong>Wunsch-Uhrzeit heute</strong><br /><small className="text-[#6f675f]">Heute, 13:00 Uhr</small></span></Button></div>}{step === 3 && <div className="grid gap-3"><Button variant={payment === "Vor Ort" ? "default" : "outline"} className="h-auto justify-start p-4 text-left" onClick={() => setPayment("Vor Ort")}><span><strong>Vor Ort bei Abholung</strong><br /><small>Barzahlung oder EC/Kreditkarte · {euro(total)}</small></span></Button><Button variant={payment === "Online" ? "default" : "outline"} className="h-auto justify-start p-4 text-left" onClick={() => setPayment("Online")}><span><strong>Online sofort zahlen</strong><br /><small>PayPal, Apple Pay, Google Pay oder Karte · Vorbereitung für Stripe</small></span></Button></div>}<DialogFooter><Button variant="ghost" onClick={() => step > 1 ? setStep(step - 1) : onOpenChange(false)}>{step > 1 && <ChevronLeft data-icon="inline-start" />}Zurück</Button><Button disabled={!canContinue} onClick={() => step < 3 ? setStep(step + 1) : onComplete()} className="rounded-full bg-[#292725] text-white">{step === 3 ? "Bestellung absenden" : "Weiter"}</Button></DialogFooter></DialogContent></Dialog>; }
function Confirmation({ orderNumber, onBack }: { orderNumber: string; onBack: () => void }) { return <main className="flex min-h-screen items-center justify-center bg-[#f5f0e8] px-5"><div className="w-full max-w-lg rounded-3xl bg-[#fffaf4] p-8 text-center shadow-xl sm:p-12"><div className="mx-auto flex size-16 items-center justify-center rounded-full bg-[#dbe7d1] text-[#4f7041]"><Check /></div><p className="mt-6 text-xs font-bold uppercase tracking-[.18em] text-[#a85b39]">Bestellung bestätigt</p><h1 className="mt-3 font-display text-5xl">Danke, wir freuen uns!</h1><p className="mt-5 text-[#6f675f]">Deine Bestellung <strong>{orderNumber}</strong> ist bei uns eingegangen. Wir bereiten alles frisch für dich zu.</p><Button onClick={onBack} className="mt-8 rounded-full bg-[#292725] text-white">Weitere Bestellung</Button></div></main>; }

export default OrderPage;
    
